name: Web App Infra Destroy - Dev
on:
  workflow_dispatch:
    branches:
    - prod
    - dev
    paths: 
    - infrastructure/dev/**
    inputs:
      approver:
        description: 'Terraform Destroy approver'     
        required: true
        default: 'jaishreej'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    #environment: dev
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }}
      WORKING_DIR: ./infrastructure/dev
      
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color -destroy
        continue-on-error: true

      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.event.inputs.approver }}

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -input=false --auto-approve
        shell: bash
        
